### ISSUE TITLE
2612 CPU overload even when idle

### ISSUE THREAD

**Issue by nnbveh** [Kautenja/PotatoChips#71] opened 2020-10-14 07:36 UTC
### Describe the bug

It starts at about 25% and quickly goes all the way up to 95-97%

### To Reproduce

1.  foo
2.  bar

### Screenshots
<img width="1400" alt="Screen Shot 2020-10-14 at 10 34 51" src="https://user-images.githubusercontent.com/39271290/95957888-e5b61080-0e32-11eb-9beb-10d6d8c65723.png">

### Environment
Mac os 10.5.5 macbook pro 16"

**Comment by Kautenja** [comment] 2020-10-14 12:19
duplicate of #66

**Closed as completed by Kautenja** 2020-10-14 12:19 UTC
Labels: duplicate

**Comment by Kautenja** [comment] 2020-10-20 15:20
@nnbveh This issue has been resolved in 1.8.0. Please stand-by for the update. 2612 now has comparable CPU usage to the other modules in this plugin :)
